name = "risk-lens"
main = "src/worker.js"
compatibility_date = "2024-01-15"

# KV Namespaces
[[kv_namespaces]]
binding = "RISK_LENS_KV"
preview_id = "preview_namespace_id"
id = "production_namespace_id"

# Environment Variables
[vars]
HUGGINGFACE_API_URL = "https://api-inference.huggingface.co/models"
ENVIRONMENT = "production"

# Environment-specific configurations
[env.staging]
name = "risk-lens-staging"
[[env.staging.kv_namespaces]]
binding = "RISK_LENS_KV"
id = "staging_namespace_id"

[env.staging.vars]
ENVIRONMENT = "staging"

[env.production]
name = "risk-lens-production"
[[env.production.kv_namespaces]]
binding = "RISK_LENS_KV"
id = "production_namespace_id"

[env.production.vars]
ENVIRONMENT = "production"